package org.bbva.kidsbankingapp.utils;

public class Queries {
	public static final String SELECT_PADRE 
		= "SELECT ID_PADRE,NOMBRE,FEC_ALTA,FEC_BAJA,ACTIVO,PASSWORD FROM KIDS.T_PADRES WHERE ID_PADRE=? AND ACTIVO=TRUE";
	public static final String SELECT_HIJO 
		= "SELECT ID_HIJO,NOMBRE,FEC_ALTA,FEC_BAJA,ACTIVO,PASSWORD FROM KIDS.T_HIJOS WHERE ID_HIJO=? AND ACTIVO=TRUE";
	public static final String SELECT_CUENTA_FROM_CUENTA_ID 
		= "SELECT ID_CUENTA,ID_HIJO,IMP_SALDO,FEC_ALTA,FEC_BAJA,ACTIVO,ID_PADRE FROM KIDS.T_CUENTAS "
			+ "WHERE ID_CUENTA = ?";
	public static final String SELECT_CUENTAS_FROM_HIJO 
		= "SELECT ID_CUENTA,ID_HIJO,IMP_SALDO,FEC_ALTA,FEC_BAJA,ACTIVO,ID_PADRE FROM KIDS.T_CUENTAS "
			+ "WHERE ID_HIJO = ?";
	public static final String SELECT_TARJETA_FROM_TARJETA_ID 
		= "SELECT ID_TARJETA,ID_HIJO,IMP_SALDO,FEC_ALTA,FEC_BAJA,ACTIVO,ID_PADRE FROM KIDS.T_TARJETAS "
		+ "WHERE ID_TARJETA = ?";
	public static final String SELECT_TARJETAS_FROM_HIJO 
		= "SELECT ID_TARJETA,ID_HIJO,IMP_SALDO,FEC_ALTA,FEC_BAJA,ACTIVO,ID_PADRE FROM KIDS.T_TARJETAS "
		+ "WHERE ID_HIJO = ?";
	public static final String SELECT_PRODUCTO
		= "SELECT ID_PRODUCTO,DESCRIPCION,IMP_PRECIO,NIVEL FROM KIDS.T_PRODUCTOS"
		+ "WHERE ID_PRODUCTO = ?";
	public static final String SELECT_PRODUCTOS
		= "SELECT ID_PRODUCTO,DESCRIPCION,IMP_PRECIO,NIVEL FROM KIDS.T_PRODUCTOS";
	public static final String SELECT_NIVELES
		= "SELECT ID_NIVEL,DESCRIPCION FROM KIDS.T_NIVELES";
	public static final String SELECT_MOVIMIENTOS
		= "SELECT ID_MOVIMIENTO,ID_CUENTA,ID_TARJETA,IMP_MOVIMIENTO,FEC_MOVIMIENTO,DESCRIPCION,IMP_SALDO,ID_PRODUCTO,ID_HIJO "
		+ "FROM KIDS.T_MOVIMIENTOS WHERE ID_CUENTA = ?";
	public static final String INSERT_PADRE = 
			"INSERT INTO KIDS.PADRES(ID_PADRE,NOMBRE,FEC_ALTA,FEC_BAJA,ACTIVO,PASSWORD) VALUES (?.?.?.?.?.?)";
	public static final String INSERT_HIJO = 
			"INSERT INTO KIDS.HIJOS (ID_PADRE,ID_HIJO,NOMBRE_HUO,FEC_ALTA,FEC_BAJA,ACTIVO,NIVEL,PASSWORD,IMP_MENSUAL) VALUES (?,?,?,?,?,?,?,?,?)";
	public static final String INSERT_CUENTA =
			"INSERT INTO KIDS.T_CUENTAS(ID_CUENTA,ID_HIJO,IMP_SALDO,FEC_ALTA,FEC_BAJA,ACTIVO,ID_PADRE) VALUES (?,?,?,?,?,?,?)";	
	public static final String INSERT_MOVIMIENTO = 
			"INSERT INTO KIDS.T_MOVIMIENTOS(ID_MOVIMIENTO,ID_CUENTA,ID_TARJETA,IMP_MOVIMIENTO,FEC_MOVIMIENTO,DESCRIPCION,IMP_SALDO,ID_PRODUCTO,ID_HIJO) VALUES (?,?,?,?,?,?,?,?,?)";	
	public static final String INSERT_TARJETA =
			"INSERT INTO KIDS.T_TARJETA (ID_TARJETA,ID_CUENTA,ID_HIJO,FEC_ALTA,FEC_BAJA,ACTIVO) VALUES (?,?,?,?,?,?)";
	public static final String ACTUALIZAR_SALDO = 
			"UPDATE KIDS.T_CUENTAS SET IMP_SALDO=? WHERE ID_CUENTA=?";
	
}
