// SCHEMA
CREATE SCHEMA IF NOT EXISTS KIDS;

CREATE TABLE IF NOT EXISTS KIDS.T_CUENTAS
(
    ID_CUENTA VARCHAR(10) NOT NULL,
    ID_HIJO VARCHAR(10)  NOT NULL,
    IMP_SALDO DECIMAL(15, 2) NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    ID_PADRE VARCHAR(10) ,
	IMP_MENSUAL DECIMAL(15, 2) NOT NULL,
    CONSTRAINT PK_CUENTAS PRIMARY KEY (ID_CUENTA, ID_HIJO)
);
MERGE INTO KIDS.T_CUENTAS(ID_CUENTA, ID_HIJO, IMP_SALDO, FEC_ALTA, FEC_BAJA, ACTIVO, ID_PADRE, IMP_MENSUAL)
	              VALUES ('500', '200', 6000, CURRENT_DATE, CURRENT_DATE, TRUE, '100', 700);
;

CREATE TABLE IF NOT EXISTS KIDS.T_HIJOS
(
    ID_PADRE VARCHAR(10)  NOT NULL,
    ID_HIJO VARCHAR(10)  NOT NULL,
    NOMBRE_HUO VARCHAR(40)  NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    NIVEL VARCHAR(4) ,
    PASSWORD VARCHAR(20)  NOT NULL,
    MAIL VARCHAR(80) NOT NULL,
    CONSTRAINT T_HIJOS_PKEY PRIMARY KEY (ID_PADRE, ID_HIJO)
);
/*
MERGE INTO KIDS.T_HIJOS(
	ID_PADRE, ID_HIJO, NOMBRE_HUO, FEC_ALTA, FEC_BAJA, ACTIVO, NIVEL, PASSWORD, MAIL)
	VALUES ('100', '200', 'JORGE GARCIA', CURRENT_DATE, CURRENT_DATE, TRUE,'6', '123456', 'JUANG@GMAIL.COM');
*/
-- TABLE: KIDS.T_MOVIMIENTOS

CREATE TABLE IF NOT EXISTS KIDS.T_MOVIMIENTOS
(
    ID_MOVIMIENTO VARCHAR(10)  NOT NULL,
    ID_CUENTA VARCHAR(10)  NOT NULL,
    ID_TARJETA VARCHAR(10)  NOT NULL,
    IMP_MOVIMIENTO DECIMAL(15, 2) NOT NULL,
    FEC_MOVIMIENTO DATE NOT NULL,
    DESCRIPCION VARCHAR(40) ,
    IMP_SALDO DECIMAL(15, 2),
    ID_PRODUCTO VARCHAR(10) ,
    ID_HIJO VARCHAR(10) ,
    CONSTRAINT PK_MOVS PRIMARY KEY (ID_MOVIMIENTO, ID_CUENTA, ID_TARJETA)
);
/*
MERGE INTO KIDS.T_MOVIMIENTOS(
	ID_MOVIMIENTO, ID_CUENTA, ID_TARJETA, IMP_MOVIMIENTO, FEC_MOVIMIENTO, DESCRIPCION, IMP_SALDO, ID_PRODUCTO, ID_HIJO)
	VALUES ('444', '500', '333', 200, CURRENT_DATE, 'EFECTIVO',550 , '155', '200');
;
*/
-- TABLE: KIDS.T_NIVELES

-- DROP TABLE KIDS.T_NIVELES;

CREATE TABLE IF NOT EXISTS KIDS.T_NIVELES
(
    ID_NIVEL VARCHAR(4)  NOT NULL,
    DESCRIPCION VARCHAR(40) ,
    CONSTRAINT T_NIVELES_PKEY PRIMARY KEY (ID_NIVEL)
);
/*
MERGE INTO KIDS.T_NIVELES(
	ID_NIVEL, DESCRIPCION)
	VALUES (6, 'EXPERTO 2');;
*/
CREATE TABLE IF NOT EXISTS KIDS.T_PADRES
(
    ID_PADRE VARCHAR(10)  NOT NULL,
    NOMBRE VARCHAR(40)  NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    PASSWORD VARCHAR(20)  NOT NULL,
	MAIL VARCHAR(80) NOT NULL,
    CONSTRAINT T_PARENTS_PKEY PRIMARY KEY (ID_PADRE)
);
/*
MERGE INTO KIDS.T_PADRES(
	ID_PADRE, NOMBRE, FEC_ALTA, FEC_BAJA, ACTIVO, PASSWORD, MAIL)
	VALUES ('100', 'SANTI ROMAN', CURRENT_DATE, CURRENT_DATE, TRUE, '123456', 'JUANG@GMAIL.COM');
-- DROP TABLE KIDS.T_PRODUCTOS;
*/
CREATE TABLE IF NOT EXISTS KIDS.T_PRODUCTOS
(
    ID_PRODUCTO VARCHAR(10)  NOT NULL,
    DESCRIPCION VARCHAR(40)  NOT NULL,
    IMP_PRECIO DECIMAL(15, 2) NOT NULL,
    NIVEL VARCHAR(3)  NOT NULL,
    ACTIVO BOOLEAN NOT NULL,
	FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    CONSTRAINT T_PRODUCTOS_PKEY PRIMARY KEY (ID_PRODUCTO)
);
/*
MERGE INTO KIDS.T_PRODUCTOS(
	ID_PRODUCTO, DESCRIPCION, IMP_PRECIO, NIVEL, ACTIVO, FEC_ALTA, FEC_BAJA)
	VALUES ('155', 'SMARTPHONE', 650, '3', TRUE, CURRENT_DATE,CURRENT_DATE);
*/
CREATE TABLE IF NOT EXISTS KIDS.T_TARJETAS
(
    ID_TARJETA VARCHAR(10)  NOT NULL,
    ID_CUENTA VARCHAR(10)  NOT NULL,
    ID_HIJO VARCHAR(10)  NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
	TIPO_TARJETA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TARJETAS PRIMARY KEY (ID_TARJETA, ID_CUENTA, ID_HIJO)
);
/*
MERGE INTO KIDS.T_TARJETAS(
	ID_TARJETA, ID_CUENTA, ID_HIJO, FEC_ALTA, FEC_BAJA, ACTIVO, TIPO_TARJETA)
	VALUES ('333', '500', '200', CURRENT_DATE, CURRENT_DATE, TRUE, 'DEBITO');
// DATA
*/
MERGE INTO KIDS.T_PADRES (ID_PADRE,NOMBRE,FEC_ALTA,FEC_BAJA,ACTIVO,PASSWORD,mail) VALUES ('PADRE1','GEPPETO',CURRENT_DATE,NULL,TRUE,'PASSWORD','geppeto@bankingapp.com');