-- BDD FUNCIONA
-- OJO, HAY QUE MANTENER EL ORDEN DE CREACIÓN DE LAS TABLAS QUE SI NO AL HACER LAS FK LAS RELATED NO EXISTEN!
DROP SCHEMA IF EXISTS "kids" CASCADE;
DROP SCHEMA IF EXISTS KIDS CASCADE;

CREATE SCHEMA KIDS;
GRANT USAGE ON SCHEMA KIDS TO PUBLIC;

DROP TABLE IF EXISTS KIDS.T_PRODUCTOS;
CREATE TABLE KIDS.T_PRODUCTOS
(
    ID_PRODUCTO CHARACTER(10)  NOT NULL,
    DESCRIPCION CHARACTER(40)  NOT NULL,
    IMP_PRECIO NUMERIC(15, 2) NOT NULL,
    NIVEL CHARACTER(3)  NOT NULL,
    CONSTRAINT T_PRODUCTOS_PKEY PRIMARY KEY (ID_PRODUCTO)
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

DROP TABLE IF EXISTS KIDS.T_NIVELES;
CREATE TABLE KIDS.T_NIVELES
(
    ID_NIVEL CHARACTER(4)  NOT NULL,
    DESCRIPCION CHARACTER(40) ,
    CONSTRAINT T_NIVELES_PKEY PRIMARY KEY (ID_NIVEL)
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

DROP TABLE IF EXISTS KIDS.T_PADRES;
CREATE TABLE KIDS.T_PADRES
(
    ID_PADRE CHARACTER(10)  NOT NULL,
    NOMBRE CHARACTER(40)  NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    PASSWORD CHARACTER(20)  NOT NULL,
	MAIL VARCHAR(80) NOT NULL,
    CONSTRAINT T_PARENTS_PKEY PRIMARY KEY (ID_PADRE)
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

COMMENT ON TABLE KIDS.T_PADRES
    IS 'TABLA PARA LOS PADRES REGISTRADOS';

DROP TABLE IF EXISTS KIDS.T_HIJOS;
CREATE TABLE KIDS.T_HIJOS
(
    ID_PADRE CHARACTER(10)  NOT NULL,
    ID_HIJO CHARACTER(10)  NOT NULL,
    NOMBRE_HUO CHARACTER(40)  NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    NIVEL CHARACTER(4) ,
    PASSWORD CHARACTER(20)  NOT NULL,
    IMP_MENSUAL NUMERIC(15, 2),
	MAIL VARCHAR(80) NOT NULL,
    CONSTRAINT T_HIJOS_PKEY PRIMARY KEY (ID_PADRE, ID_HIJO),
    CONSTRAINT FK2_HIJOS FOREIGN KEY (NIVEL)
        REFERENCES KIDS.T_NIVELES (ID_NIVEL) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_HIJOS FOREIGN KEY (ID_PADRE)
        REFERENCES KIDS.T_PADRES (ID_PADRE) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

COMMENT ON TABLE KIDS.T_HIJOS
    IS 'TABLA PARA LOS HIJOS REGISTRADOS';


DROP TABLE IF EXISTS KIDS.T_CUENTAS;
CREATE TABLE KIDS.T_CUENTAS
(
    ID_CUENTA CHARACTER(10)  NOT NULL,
    ID_HIJO CHARACTER(10)  NOT NULL,
    IMP_SALDO NUMERIC(15, 2) NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    ID_PADRE CHARACTER(10) ,
    CONSTRAINT PK_CUENTAS PRIMARY KEY (ID_CUENTA, ID_HIJO),
    CONSTRAINT FK_CUENTAS FOREIGN KEY (ID_HIJO, ID_PADRE)
        REFERENCES KIDS.T_HIJOS (ID_HIJO, ID_PADRE) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

DROP TABLE IF EXISTS KIDS.T_TARJETAS;
CREATE TABLE KIDS.T_TARJETAS
(
    ID_TARJETA CHARACTER(10)  NOT NULL,
    ID_CUENTA CHARACTER(10)  NOT NULL,
    ID_HIJO CHARACTER(10)  NOT NULL,
    FEC_ALTA DATE NOT NULL,
    FEC_BAJA DATE,
    ACTIVO BOOLEAN NOT NULL,
    CONSTRAINT PK_TARJETAS PRIMARY KEY (ID_TARJETA, ID_CUENTA, ID_HIJO),
    CONSTRAINT T_TARJETAS_ID_CUENTA_FKEY FOREIGN KEY (ID_HIJO, ID_CUENTA)
        REFERENCES KIDS.T_CUENTAS (ID_HIJO, ID_CUENTA) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

DROP TABLE IF EXISTS KIDS.T_MOVIMIENTOS;
CREATE TABLE KIDS.T_MOVIMIENTOS
(
    ID_MOVIMIENTO CHARACTER(10)  NOT NULL,
    ID_CUENTA CHARACTER(10)  NOT NULL,
    ID_TARJETA CHARACTER(10)  NOT NULL,
    IMP_MOVIMIENTO NUMERIC(15, 2) NOT NULL,
    FEC_MOVIMIENTO DATE NOT NULL,
    DESCRIPCION CHARACTER(40) ,
    IMP_SALDO NUMERIC(15, 2),
    ID_PRODUCTO CHARACTER(10) ,
    ID_HIJO CHARACTER(10) ,
    CONSTRAINT PK_MOVS PRIMARY KEY (ID_MOVIMIENTO, ID_CUENTA, ID_TARJETA),
    CONSTRAINT FK_MOVS FOREIGN KEY (ID_TARJETA, ID_HIJO, ID_CUENTA)
        REFERENCES KIDS.T_TARJETAS (ID_TARJETA, ID_HIJO, ID_CUENTA) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE PG_DEFAULT;

COMMIT;