// Schema
CREATE SCHEMA IF NOT EXISTS kids;

CREATE TABLE IF NOT EXISTS kids.T_CUENTAS
(
    ID_CUENTA varchar(10) NOT NULL,
    ID_HIJO varchar(10)  NOT NULL,
    IMP_SALDO decimal(15, 2) NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    ID_PADRE varchar(10) ,
	IMP_MENSUAL decimal(15, 2) NOT NULL,
    CONSTRAINT PK_CUENTAS PRIMARY KEY (ID_CUENTA, ID_HIJO)
)
MERGE INTO kids.T_CUENTAS(
	ID_CUENTA, ID_HIJO, IMP_SALDO, FEC_ALTA, FEC_BAJA, ACTIVO, ID_PADRE, IMP_MENSUAL)
	VALUES ('500', '200', 6000, CURRENT_DATE, CURRENT_DATE, TRUE, 100, 700);

;

CREATE TABLE IF NOT EXISTS kids.T_HIJOS
(
    ID_PADRE varchar(10)  NOT NULL,
    ID_HIJO varchar(10)  NOT NULL,
    NOMBRE_HUO varchar(40)  NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    NIVEL varchar(4) ,
    PASSWORD varchar(20)  NOT NULL,
    MAIL varchar(80) NOT NULL,
    CONSTRAINT T_HIJOS_pkey PRIMARY KEY (ID_PADRE, ID_HIJO)
)
MERGE INTO kids.T_HIJOS(
	ID_PADRE, ID_HIJO, NOMBRE_HUO, FEC_ALTA, FEC_BAJA, ACTIVO, NIVEL, PASSWORD, MAIL)
	VALUES ('100', '200', 'JORGE GARCIA', CURRENT_DATE, CURRENT_DATE, TRUE,'6', '123456', 'JUANG@GMAIL.COM');

-- Table: kids.T_MOVIMIENTOS

CREATE TABLE IF NOT EXISTS kids.T_MOVIMIENTOS
(
    ID_MOVIMIENTO varchar(10)  NOT NULL,
    ID_CUENTA varchar(10)  NOT NULL,
    ID_TARJETA varchar(10)  NOT NULL,
    IMP_MOVIMIENTO decimal(15, 2) NOT NULL,
    FEC_MOVIMIENTO date NOT NULL,
    DESCRIPCION varchar(40) ,
    IMP_SALDO decimal(15, 2),
    ID_PRODUCTO varchar(10) ,
    ID_HIJO varchar(10) ,
    CONSTRAINT PK_MOVS PRIMARY KEY (ID_MOVIMIENTO, ID_CUENTA, ID_TARJETA)
)
MERGE INTO kids.T_MOVIMIENTOS(
	ID_MOVIMIENTO, ID_CUENTA, ID_TARJETA, IMP_MOVIMIENTO, FEC_MOVIMIENTO, DESCRIPCION, IMP_SALDO, ID_PRODUCTO, ID_HIJO)
	VALUES ('444', '500', '333', 200, CURRENT_DATE, 'EFECTIVO',550 , '155', '200');
;

-- Table: kids.T_NIVELES

-- DROP TABLE kids.T_NIVELES;

CREATE TABLE IF NOT EXISTS kids.T_NIVELES
(
    ID_NIVEL varchar(4)  NOT NULL,
    DESCRIPCION varchar(40) ,
    CONSTRAINT T_NIVELES_pkey PRIMARY KEY (ID_NIVEL)
)
MERGE INTO kids.T_NIVELES(
	ID_NIVEL, DESCRIPCION)
	VALUES (6, 'EXPERTO 2');;

CREATE TABLE IF NOT EXISTS kids.T_PADRES
(
    ID_PADRE varchar(10)  NOT NULL,
    NOMBRE varchar(40)  NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    PASSWORD varchar(20)  NOT NULL,
	MAIL varchar(80) NOT NULL,
    CONSTRAINT T_PARENTS_pkey PRIMARY KEY (ID_PADRE)
)
MERGE INTO kids.T_PADRES(
	ID_PADRE, NOMBRE, FEC_ALTA, FEC_BAJA, ACTIVO, PASSWORD, MAIL)
	VALUES ('100', 'SANTI ROMAN', CURRENT_DATE, CURRENT_DATE, TRUE, '123456', 'JUANG@GMAIL.COM');
-- DROP TABLE kids.T_PRODUCTOS;

CREATE TABLE IF NOT EXISTS kids.T_PRODUCTOS
(
    ID_PRODUCTO varchar(10)  NOT NULL,
    DESCRIPCION varchar(40)  NOT NULL,
    IMP_PRECIO decimal(15, 2) NOT NULL,
    NIVEL varchar(3)  NOT NULL,
    ACTIVO boolean NOT NULL,
	FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    CONSTRAINT T_PRODUCTOS_pkey PRIMARY KEY (ID_PRODUCTO)
)
MERGE INTO kids.T_PRODUCTOS(
	ID_PRODUCTO, DESCRIPCION, IMP_PRECIO, NIVEL, ACTIVO, FEC_ALTA, FEC_BAJA)
	VALUES ('155', 'SMARTPHONE', 650, '3', TRUE, CURRENT_DATE,CURRENT_DATE);

CREATE TABLE IF NOT EXISTS kids.T_TARJETAS
(
    ID_TARJETA varchar(10)  NOT NULL,
    ID_CUENTA varchar(10)  NOT NULL,
    ID_HIJO varchar(10)  NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
	TIPO_TARJETA varchar(20) NOT NULL,
    CONSTRAINT PK_TARJETAS PRIMARY KEY (ID_TARJETA, ID_CUENTA, ID_HIJO)
)
MERGE INTO kids.T_TARJETAS(
	ID_TARJETA, ID_CUENTA, ID_HIJO, FEC_ALTA, FEC_BAJA, ACTIVO, TIPO_TARJETA)
	VALUES ('333', '500', '200', CURRENT_DATE, CURRENT_DATE, TRUE, 'DEBITO');
// Data
INSERT INTO KIDS.T_PADRES (ID_PADRE,NOMBRE,FEC_ALTA,FEC_BAJA,ACTIVO,PASSWORD) VALUES ('padre1','Geppeto',CURRENT_DATE,NULL,TRUE,'password');