// Schema
CREATE SCHEMA IF NOT EXISTS kids;

CREATE TABLE IF NOT EXISTS kids.T_NIVELES
(
    ID_NIVEL varchar(4)  NOT NULL,
    DESCRIPCION varchar(40) ,
    CONSTRAINT T_NIVELES_pkey PRIMARY KEY (ID_NIVEL)
);

MERGE INTO KIDS.T_NIVELES (ID_NIVEL,DESCRIPCION) VALUES ('0001','INICIAL');
MERGE INTO KIDS.T_NIVELES (ID_NIVEL,DESCRIPCION) VALUES ('0002','NOVATO');
MERGE INTO KIDS.T_NIVELES (ID_NIVEL,DESCRIPCION) VALUES ('0003','INTERMEDIO');
MERGE INTO KIDS.T_NIVELES (ID_NIVEL,DESCRIPCION) VALUES ('0043','EXPERTO');

CREATE TABLE IF NOT EXISTS kids.T_PRODUCTOS
(
    ID_PRODUCTO varchar(10)  NOT NULL,
    DESCRIPCION varchar(40)  NOT NULL,
    IMP_PRECIO decimal(15, 2) NOT NULL,
    ACTIVO BOOLEAN NOT NULL,
    NIVEL varchar(3)  NOT NULL,
    CONSTRAINT T_PRODUCTOS_pkey PRIMARY KEY (ID_PRODUCTO)
);

MERGE INTO KIDS.T_NIVELES (ID_NIVEL,DESCRIPCION) VALUES ('PR0','PRODUCTO 0');


CREATE TABLE IF NOT EXISTS kids.T_PADRES
(
    ID_PADRE varchar(10)  NOT NULL,
    NOMBRE varchar(40)  NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    PASSWORD varchar(20)  NOT NULL,
    CONSTRAINT T_PARENTS_pkey PRIMARY KEY (ID_PADRE)
);

CREATE TABLE IF NOT EXISTS kids.T_HIJOS
(
    ID_PADRE varchar(10)  NOT NULL,
    ID_HIJO varchar(10)  NOT NULL,
    NOMBRE_HUO varchar(40)  NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    NIVEL varchar(4) ,
    PASSWORD varchar(20)  NOT NULL,
    IMP_MENSUAL decimal(15, 2),
    CONSTRAINT T_HIJOS_pkey PRIMARY KEY (ID_PADRE, ID_HIJO)
);

CREATE TABLE IF NOT EXISTS kids.T_CUENTAS
(
    ID_CUENTA varchar(10) NOT NULL,
    ID_HIJO varchar(10)  NOT NULL,
    IMP_SALDO decimal(15, 2) NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    ID_PADRE varchar(10) ,
    CONSTRAINT PK_CUENTAS PRIMARY KEY (ID_CUENTA, ID_HIJO)
)
;
CREATE TABLE IF NOT EXISTS kids.T_TARJETAS
(
    ID_TARJETA varchar(10)  NOT NULL,
    ID_CUENTA varchar(10)  NOT NULL,
    ID_HIJO varchar(10)  NOT NULL,
    FEC_ALTA date NOT NULL,
    FEC_BAJA date,
    ACTIVO boolean NOT NULL,
    CONSTRAINT PK_TARJETAS PRIMARY KEY (ID_TARJETA, ID_CUENTA, ID_HIJO)
);
-- Table: kids.T_MOVIMIENTOS
CREATE TABLE IF NOT EXISTS kids.T_MOVIMIENTOS
(
    ID_MOVIMIENTO varchar(10)  NOT NULL,
    ID_CUENTA varchar(10)  NOT NULL,
    ID_TARJETA varchar(10)  NOT NULL,
    IMP_MOVIMIENTO decimal(15, 2) NOT NULL,
    FEC_MOVIMIENTO date NOT NULL,
    DESCRIPCION varchar(40) ,
    IMP_SALDO decimal(15, 2),
    ID_PRODUCTO varchar(10) ,
    ID_HIJO varchar(10) ,
    CONSTRAINT PK_MOVS PRIMARY KEY (ID_MOVIMIENTO, ID_CUENTA, ID_TARJETA)
)
;

-- Table: kids.T_NIVELES

-- DROP TABLE kids.T_NIVELES;

// Data
MERGE INTO KIDS.T_PADRES (ID_PADRE,NOMBRE,FEC_ALTA,FEC_BAJA,ACTIVO,PASSWORD) VALUES ('padre1','Geppeto',CURRENT_DATE,NULL,TRUE,'password');